[project]
name = "imhpa-api"
version = "0.0.1"
description = "API wrapper for IMHPA data"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "httpx>=0.28.1",
    "jupyter>=1.1.1",
    "lxml>=6.0.2",
    "pandas>=3.0.0",
    "pyarrow>=23.0.0",
]
